apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  01-init-databases.sql: | 
    CREATE DATABASE authdb;
    CREATE DATABASE orderdb;
    CREATE DATABASE userservicedb;
    
    GRANT ALL PRIVILEGES ON DATABASE authdb TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE orderdb TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE userservicedb TO postgres;